spring.datasource.url=jdbc:mysql://root:TmWFjhCGXQshVqrAYzlDwtYfiKuYvRqL@switchyard.proxy.rlwy.net:20106/railway
spring.datasource.username=root
spring.datasource.password=TmWFjhCGXQshVqrAYzlDwtYfiKuYvRqL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080